# Base configs
baseurl: "https://photography.rampatra.com"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-173258797-1"

# UI configs
title: "Photography by Shawn S.T"
subtitle: "See the world through my eyes!"
author: "Shawn S.T"
header:
 title: "Photography"
 subtitle: "by Shawn S.T"
footer:
 name: "Hey there, my name is Shawn S.T"
 bio: "I'm a college student who loves photography. I'm always getting some fantastic things going on in my head."
 github: "More Imaginary，More Powerful，More Comfortable；和我取得联系  <a href=\"https://weibo.com/u/6280167955\">点击这里</a> ;)"
web_design: "AJ"
social_urls:
  facebook: "https://weibo.com/u/6280167955"
  twitter: "https://vk.com/id560091364"
  instagram: "https://www.instagram.com/shawns.t/"
  dribbble: "https://space.bilibili.com/432301"
  linkedin: "https://github.com/GarGarfie/"
  github: "https://www.youtube.com/"
